title: blog
email: coftware@gmail.com
description: >- # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.massapi.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username:  peaklau2008

# Build settings
#theme: minima
plugins:
  # existing plugins
  - jekyll-feed  
  - jekyll-remote-theme
remote_theme: "jekyll/minima"


exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - README.md


minima:
  skin: dark
  show_excerpts: true
  excerpt_separator: "<!--more-->"    
  nav_pages:
    - about.md  
    - bookmarks.md      
  social_links:
    - title: peaklau2008
      icon: github
      url: "https://github.com/peaklau2008"    